### ISSUE TITLE
MA Creation Wizard: Exception from HRESULT: 0x80230703

### ISSUE THREAD

**Issue by msmith-moq** [sorengranfeldt/psma#11]
If you leave the Import Script, Export Script and/or Password Management Script input field(s) blank you receive this cryptic error:
![image](https://user-images.githubusercontent.com/37351722/53219520-5d5e8700-36b4-11e9-9eb7-3198d486cf18.png)

**Comment by spiderchicke2** [comment]
Hi there

I'm facing the same issue.
Does one know how to get rid of it?

Thanks

**Comment by jlonnqvist** [comment]
Just make sure to enter a path to the password management script.
If you don't use password management, just create an empty .ps1 script and point to that.
