### ISSUE TITLE
Export Issue - ChangedAttributeNames is null

### ISSUE THREAD

**Issue by JeremiahRush** [sorengranfeldt/psma#13]
Working on standing up the PSMA for management of EXO policy/address management. Imports/schema work fine. Export was working, and I was working out the remaining bugs when the exports stopped working all together.

Dumping the pipe content up front, I see that $_.'[ChangedAttributeNames]' is null now. Restarted sync service, and then server... still sending that value as null. The rest of the pipe content is fine complete. 

*No changes were made the the MA itself before or after the CANs stopped coming through.

**Comment by sorengranfeldt** [comment]
Sounds strange. I have this working a numerous installations. Sounds like a corrupt CS or similar. If you do a Full Import and Full Sync is the problem still there? Also maybe try delete the connector space and reimport and sync

**Comment by JeremiahRush** [comment]
Thank you for the quick reply. Issue was still present after a full sync cycle. Being my dev environment, I deleted the MA and rebuilt. The ChangedAttributeNames attribute was populating again correctly. I really should have tried just deleting the CS and re-importing first. I'll mark this as closed and update if we see it come up again.
