### ISSUE TITLE
schema.ps1 file has correct syntax. new attributes not ingesting into MV

### ISSUE THREAD

**Issue by hamishmcca** [sorengranfeldt/psma#15]
having trouble with adding new schema into MV
have increased righst on auth id, sync service id.
have used debugview. looks ok
schema syntax ok. tried 4-5 different files from traps.
am i missing something here ?

**Comment by hamishmcca** [comment]
MA refresh appears to run through fine. yet no new attributes appear in MV schema. MV designer shows nothing new

**Comment by sorengranfeldt** [comment]
A schema refresh doesn’t create MV attributes, only CS attributes. MV attributes must be created manually

**Comment by hamishmcca** [comment]
Hanson manual create in MV designer ?




Get Outlook for Android







On Thu, Jun 11, 2020 at 2:48 PM +1000, "Søren Granfeldt" <notifications@github.com> wrote:
















A schema refresh doesn’t create MV attributes, only CS attributes. MV attributes must be created manually

**Comment by hamishmcca** [comment]
Thanks Soren




Working on a new install at NBN.




Getting there.




Hamish




Get Outlook for Android







On Thu, Jun 11, 2020 at 2:50 PM +1000, "Hamish Mccarthy" <hamish.mccarthy@bigpond.com> wrote:










Hanson manual create in MV designer ?




Get Outlook for Android







On Thu, Jun 11, 2020 at 2:48 PM +1000, "Søren Granfeldt" <notifications@github.com> wrote:
















A schema refresh doesn’t create MV attributes, only CS attributes. MV attributes must be created manually

**Comment by hamishmcca** [comment]
manually adding them into MV sorted it.  Thanks Soren
