### ISSUE TITLE
Object Rename

### ISSUE THREAD

**Issue by sylvainclb** [sorengranfeldt/psma#17]
Hello, 

I would like to known why the object rename is not supported by the MA. Is there any specific reason?

`cap.ObjectRename = false;` in MA.Capabilities.cs

Thank you!

**Comment by sorengranfeldt** [comment]
Hi, it was a design decision made in the initial version. What problem are you trying to solve?

**Comment by sylvainclb** [comment]
Hi,

I plan to use it to do import and export on an OID, to manage users and groups. The users need to be moved in a disabled OU, when they are disabled.

**Comment by sorengranfeldt** [comment]
You can do that just fine. Should have nothing to do with that setting

**Comment by sylvainclb** [comment]
I am not sure to follow you. I use the DistinguishedName as DN/Anchor, because I need to define the same anchor attribute for all objects in the PSMA Schema: I need to define technical objects such as domain, orclContainer, organizationalUnit, and dn is the only one in common (no Guid)

The rename is done by SR, and I hit an error when trying to move user for one OU to another.

Maybe I missed something?

**Comment by sorengranfeldt** [comment]
I wouldn’t use DN as anchor. Use an immutable attribute like a guid and use DN for references

**Comment by sylvainclb** [comment]
Hello,

Yes, firstly I want to use an immutable attribute but the orclguid was not visible when I requested an user. I looked deeper on this and found the reason.

In fact, I am on an old version of OID, and can use an SSL connect to bind on the directory due to the weak cipher. When you bind to the directory without SSL, the orclguid is not retrieved; You need to explicit request it to be able to retrive it. 

Thank for your time Soren!

Cheers, 
Sylvain
