### ISSUE TITLE
Rules Extensions not supported?

### ISSUE THREAD

**Issue by Amethi** [sorengranfeldt/psma#21]
Hello! Thanks for this wonderful MA :) I'm running version 5.5.3.1309 and am unable to set a rules against against the MA. Is this intentional? The Select button is greyed out.

**Comment by sorengranfeldt** [comment]
If you mean Rules Extension, that is supported. Otherwise please elaborate and provide screenshots maybe

**Comment by Amethi** [comment]
Yes, Rules Extension. When viewing the properties of the MA on the Configure Extensions tab, everythings is greyed out, except the option for Enable password management. Sorry, can't get screenshot out.

**Comment by sorengranfeldt** [comment]
The box will be enabled when you create the first advanced flow. That’s standard behavior in Sync

**Comment by Amethi** [comment]
Superb, thanks. It's been some time since I create a RE-based flow :)

**Comment by sorengranfeldt** [comment]
Has this been resolved? If yes, please close the issue.

**Comment by Amethi** [comment]
Yes, all good, thanks.
