### ISSUE TITLE
unable to disable the provisioning

### ISSUE THREAD

**Issue by mirsa3615** [sorengranfeldt/psma#22]
Hello,
inside my import script, I need to disable the provisioning rules extension by using "Set-MVProvisioningRulesExtension -Enabled $false" (from the lithnet Miiserver automation module)
but this command returns : ERROR: Error reading the metaverse data: {0}.
when I run the import script manually it's working but it's not working inside the MA.
My configuration 
MIM 2016 version 4.6.258
Lithnet : 1.0.7783
PS : 4.8.03761

**Comment by sorengranfeldt** [comment]
This seem to be more an issue with Lithnet than with the PSMA. You may want to post the issue there instead.

**Comment by mirsa3615** [comment]
Thank you for your quick answer.
I think that is because we can't modify the configuration when the MA is running.
I will then disable the provisioning before starting the PS MA.

**Comment by sorengranfeldt** [comment]
Okay. Just a quick note - it seems like a flacky design if you need to enable/disable provisioning during runs. If it was me, I'd look into a solution where that isn't necessary.

Please close issue if it has been answered.

**Comment by mirsa3615** [comment]
thank you very much for your great work 👍
