### ISSUE TITLE
Ability to set Schema Attributes as ImportOnly or ExportOnly

### ISSUE THREAD

**Issue by benoitboudeville75** [sorengranfeldt/psma#23]
Hello,

I have a need for a customer to replace the MS PowerShell MA but something better :)
In a custom MA of my own, I recall exploring attribute definitions when building the Schema and ability to create ImportOnly and ExportOnly attributes.

In particular here, my need is to have ExportOnly attributes that are used at provisioning time only, and therefore do not need to be available (and is actually NOT available) when doing the Delta Import confirmation.

For this matter I propose the following:

1) add the ImportOnly/ExportOnly properties to the AttributeDefinition class
2) when reading the attribute, search for ImportOnly-/ExportOnly- keyword as it's the case for Anchor- and set the properties accodingly
3) when creating SchemaAttribute objects, set the AttributeOperation property accordingly

Now given the way the flag is defined in the name:

1) technically speaking and attribute can only be ImportOnly or ExportOnly and is by default ImportExport
2) anchor attribute is by designed excluded from the feature

Codes changes are quite minor but benefits are great, I think :)

1) change in the AttributeDefinition class (add two properties)
2) change in the GetSchema method to read the flag from the name + to create the SchemaAttribute objects using the 3rd parameter (of enum type AttributeOperation)

Let me know what you think. If you don't want to make it to the main codebase I'll fork my own version.

Thanks,
Benoit.

**Comment by sorengranfeldt** [comment]
Hi. Any reason why you cannot just set the attributes only on provision? Currently I don't have the time to expand the PSMA with the things you suggest. Also, documentation and samples need to be updated if the functionality is changed and backwards compatibility needs to be tested and maintained as this MA is just very much around the world. If you're in a hurry and really need this, I think you should run your own fork. If I get the time, I could consider similar features for futures versions of the MA.

**Comment by benoitboudeville75** [comment]
Hello, Søren and best wishes for 2022.

I already have made the change in the code, it was quite easy and it’s being tested extensively in my development lab.
I’m a good writer too, I could even document the feature too, even provide samples.

Reason for the request is historical but also mostly because it’s a built-in feature of some MA, and I’m saying to myself “why isn’t it supported here…?”

Anyway, setting the attribute at provisioning is indeed what’s done, but that doesn’t change the fact that MIM needs to confirm the export. Which doesn’t happen with an ExportOnly attribute typically, since it’s not expected to be read back from the Datasource. I prefer not having an “exported-change-not-reimported” warning, neither, worse, having to disable Confirms (and I think there’s not way to do so in your PSMA). ExportOnly attributes are the best approach for such scenarios.

Anyway, thanks anyway for taking the time to respond. If you need contributors, you have my contact info now, I’ve coded a lot for MIM and even my own MAs too.

Cheers,
Benoit.

**Comment by sorengranfeldt** [comment]
I would be happy to check out a pull request at some point in time, also for the documentation. I can review when I get the time. I cannot promise, however, when I'll get the time.

**Comment by benoitboudeville75** [comment]
I’m suck with git but I think I managed to create my own branch and you should be able to compare ==> benoitboudeville75:master
Added ImportOnly/ExportOnly specifiers for Schema Attributes by benoitboudeville75 · Pull Request #24 · sorengranfeldt/psma (github.com)<https://github.com/sorengranfeldt/psma/pull/24/commits/09bcf67f99ef7e9076540cab320a8e6cf6a40cb0>

For the doc it will take me a little more time as, just like you, I must work for my company and customers, too 😉
I’ll certainly should be able to work on the doc later today or tomorrow.

Cheers,
Benoit

**Comment by sorengranfeldt** [comment]
Added in PR #24

**Comment by benoitboudeville75** [comment]
Hi Søren, I saw you merged the changes ! Wow that was fast. Indeed, as I told you, changes were quite minor overall ;)
I saw you also changed the flexible schema documentation too. Thanks!

Cheers,
Benoit.
