### ISSUE TITLE
Powershell Core / 7+ support

### ISSUE THREAD

**Issue by OtterKring** [sorengranfeldt/psma#27]
Is there an easy way to make PSMA use PS Core instead of WinPS? Some modules like PnP.Powershell version 2+ do not support WinPS anymore.

I tried calling my script with pwsh.exe in the script called by MIM, but handling the global variables PSMA supplied for talking to MIM is a nightmare, at least on my level of knowledge.

**Comment by sorengranfeldt** [comment]
Unfortunately not. We’re stuck on the .NET Framework since the Sync host ECMA framework runs on this. I’ve found no solution for moving to Core yet

**Comment by sorengranfeldt** [comment]
There is a version on the way that will support PS7+
