### ISSUE TITLE
Schema Definition File Build Tool

### ISSUE THREAD

**Issue by darrenjrobinson** [sorengranfeldt/psma#3]
A side utility that can be used to leverage a standalone PowerShell script that connects to a Service either through API or the use of PowerShell Module(s) that returns;
- objects of interest (e.g. User, Group, Contact)
- builds a Schema Definition file for the PSMA of the returned ObjectTypes along with their attributeTypes (e.g Integer, Boolean, String, Multivalue, Reference)

The resultant Schema Definition file then reflects the target system to quickly get started with building a new PSMA.

**Comment by sorengranfeldt** [comment]
Have any sample script that could be a starter template?
