### ISSUE TITLE
missing Granfeldt.PowerShell.ManagementAgent.dll

### ISSUE THREAD

**Issue by coreyeclements** [sorengranfeldt/psma#4]
I have scoured the internet to determine how I could be the only one finding that the "Granfeldt.PowerShell.ManagementAgent.dll" file is not included in the psma zip download. Of course this causes the install to be incomplete when the ps install script fails to copy this dll from the source folder to the MIM sync extensions folder.

the install script assigns the variable:  $mafilename = "Granfeldt.PowerShell.ManagementAgent.dll"
and then later copies it with:  copy-item "$mafilename" -destination "$extensionsfolder"

Looking in the file list on github, it indeed is not present either.

Am I missing something right in front of me where no-one has seemed to ran across this problem?

**Comment by sorengranfeldt** [comment]
Have a look in the release downloads available in the Code section. Those should have the DLL

Thank you.

Med venlig hilsen
Søren Granfeldt

On 16 May 2018, at 22.21, Corey <notifications@github.com<mailto:notifications@github.com>> wrote:


I have scoured the internet to determine how I could be the only one finding that the "Granfeldt.PowerShell.ManagementAgent.dll" file is not included in the psma zip download. Of course this causes the install to be incomplete when the ps install script fails to copy this dll from the source folder to the MIM sync extensions folder.

the install script assigns the variable: $mafilename = "Granfeldt.PowerShell.ManagementAgent.dll"
and then later copies it with: copy-item "$mafilename" -destination "$extensionsfolder"

Looking in the file list on github, it indeed is not present either.

Am I missing something right in front of me where no-one has seemed to ran across this problem?

**Comment by sorengranfeldt** [comment]
You should be able to find the DLL in the releases here - https://github.com/sorengranfeldt/psma/releases

Where you able to find this?

**Comment by coreyeclements** [comment]
Thank you. one of the downloads contained just the ps1, xml and dll - but named the same as the other downloads. The others contain the entire package but no dll. Thank you :)
