### ISSUE TITLE
How to import ObjectSID?

### ISSUE THREAD

**Issue by lehtoj** [sorengranfeldt/psma#9]
I am at my wits end here. ObjectSID should be of type binary and PSMA expects `[byte[]]`. But I have not figured out how to convert `[System.Security.Principal.SecurityIdentifier]` in such a way that PSMA accepts it during import.

I have tried `[System.Security.Principal.SecurityIdentifier]`, `[byte[]]` as well as converting `[byte[]]`
 into hexadecimal value by `($byteArray | ForEach-Object { '{0:X2}' -f $_ })`, `[System.Convert]::ToBase64String($byteArray)` and `Format-Hex -InputObject $byteArray`

None of the above have worked.

Pretty please, advise.

Edit: I fixed the problem at last.

```
function Convert-SIDToByteArray {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true, Position = 0, ValueFromPipeline = $true)]
        [System.Security.Principal.SecurityIdentifier]
        $Sid
    )

    $byteArray = New-Object System.Byte[]($Sid.BinaryLength)
    $Sid.GetBinaryForm($byteArray, 0)
    $byteArray
}
```

The function above always returns `[System.Object[]]` even when the last line is edited as `[byte[]]$byteArray` or `$byteArray -as [byte[]]`. I had to do `(Convert-SIDToByteArray $adObject.objectSid) -as [byte[]]` to finally get import to accept the values.

**Comment by sorengranfeldt** [comment]
Glad you solved the issue yourself. Great work,
